mt5_jurisdiction_validation:
  description: Contains rules to be applied on mt5 account to check if it is considered active
  ruleset:
    - mt5_account.account_proof_status_allowed
    - mt5_account.account_poa_status_allowed

new_mt5_dez_account:
  description: Rules applied on MT5 and DerivEZ account creation
  ruleset:
    - trading_account.client_account_type_should_be_supported
    - trading_account.trading_platform_supported_by_residence_and_regulation
    - type: conditional
      on: account_type
      rules_per_value:
        real:
          - trading_account.client_should_be_real
        financial:
          - trading_account.client_should_be_real
        gaming:
          - trading_account.client_should_be_real
        demo:
          - pass
