---
CALL_RDBEAR_1454284800_1454889600_102.3305: 0.339629238721528
CALL_RDBEAR_1454284800_1454889600_105.1283: 0.294908682507736
CALL_RDBEAR_1454284800_1454889600_108.0495: 0.252464905588926
CALL_RDBEAR_1454284800_1454889600_96.9142: 0.436354040800254
CALL_RDBEAR_1454284800_1454889600_99.6072: 0.38672804405167
CALL_RDBEAR_1454284800_1455494400_100.7961: 0.323000423372505
CALL_RDBEAR_1454284800_1455494400_104.7153: 0.279302816658393
CALL_RDBEAR_1454284800_1455494400_108.7870: 0.238692493487633
CALL_RDBEAR_1454284800_1455494400_113.0864: 0.200975015799249
CALL_RDBEAR_1454284800_1455494400_96.9639: 0.370050161802761
CALL_RDBULL_1454284800_1454889600_102.9802: 0.337789572205765
CALL_RDBULL_1454284800_1454889600_106.1646: 0.293176676431774
CALL_RDBULL_1454284800_1454889600_109.5011: 0.250862425321526
CALL_RDBULL_1454284800_1454889600_96.8476: 0.434373750462814
CALL_RDBULL_1454284800_1454889600_99.8913: 0.384805633421404
CALL_RDBULL_1454284800_1455494400_101.5788: 0.320453266084461
CALL_RDBULL_1454284800_1455494400_106.0492: 0.276917527744459
CALL_RDBULL_1454284800_1455494400_110.7163: 0.236495144379526
CALL_RDBULL_1454284800_1455494400_115.6691: 0.198984548778678
CALL_RDBULL_1454284800_1455494400_97.2294: 0.367369501975534
CALL_R_100_1454284800_1454889600_100.96: 0.327748925155359
CALL_R_100_1454284800_1454889600_102.74: 0.283558106254578
CALL_R_100_1454284800_1454889600_104.57: 0.242038682134253
CALL_R_100_1454284800_1454889600_97.48: 0.423504938884312
CALL_R_100_1454284800_1454889600_99.22: 0.37424037557049
CALL_R_100_1454284800_1455494400_101.94: 0.263812211504289
CALL_R_100_1454284800_1455494400_104.48: 0.224452137550484
CALL_R_100_1454284800_1455494400_107.12: 0.188184613125041
CALL_R_100_1454284800_1455494400_97.00: 0.35266022833799
CALL_R_100_1454284800_1455494400_99.46: 0.306446485281179
CALL_R_25_1454284800_1454889600_100.060: 0.102993370118018
CALL_R_25_1454284800_1454889600_100.496: 0.0822269996326045
CALL_R_25_1454284800_1454889600_100.941: 0.064526323433048
CALL_R_25_1454284800_1454889600_99.186: 0.155932881027254
CALL_R_25_1454284800_1454889600_99.626: 0.127321782327729
CALL_R_25_1454284800_1455494400_100.120: 0.0368424069283382
CALL_R_25_1454284800_1455494400_100.738: 0.0277956952127049
CALL_R_25_1454284800_1455494400_101.370: 0.0205788099995562
CALL_R_25_1454284800_1455494400_98.886: 0.0623523619476386
CALL_R_25_1454284800_1455494400_99.506: 0.0481611390755284
CALL_RDBEAR_1454284800_1454325120_100.0000: 0
PUT_RDBEAR_1454284800_1454287488_100.0000: 0.93813
CALL_RDBEAR_1454284800_1454284979_100.0100: 0.22754
PUT_RDBEAR_1454284800_1454284811_100.0100: 0.9344
CALL_RDBEAR_1454284800_1454365440_100.0000: 0
PUT_RDBEAR_1454284800_1454290176_100.0000: 0.98525
CALL_RDBEAR_1454284800_1454285158_100.0100: 0.20924
PUT_RDBEAR_1454284800_1454284823_100.0100: 0.86824
CALL_RDBULL_1454284800_1454325120_100.0000: 0.99997
PUT_RDBULL_1454284800_1454287488_100.0000: 0.00355
CALL_RDBULL_1454284800_1454284979_100.0100: 0.63494
PUT_RDBULL_1454284800_1454284811_100.0100: 0.89227
CALL_RDBULL_1454284800_1454365440_100.0000: 0.99993
PUT_RDBULL_1454284800_1454290176_100.0000: 7e-05
CALL_RDBULL_1454284800_1454285158_100.0100: 0.76889
PUT_RDBULL_1454284800_1454284823_100.0100: 0.7663
CALL_R_100_1454284800_1454325120_100.00: 0.49913
PUT_R_100_1454284800_1454287488_100.00: 0.50022
CALL_R_100_1454284800_1454365440_100.00: 0.49876
PUT_R_100_1454284800_1454290176_100.00: 0.50031
CALL_R_25_1454284800_1454325120_100.000: 0.49913
PUT_R_25_1454284800_1454287488_100.000: 0.50022
CALL_R_25_1454284800_1454284979_100.100: 0.00024
CALL_R_25_1454284800_1454365440_100.000: 0.49876
PUT_R_25_1454284800_1454290176_100.000: 0.50031
CALL_R_25_1454284800_1454285158_100.100: 0.00671
EXPIRYMISS_RDBEAR_1454284800_1454284800_103.0000_94.0000: 0
EXPIRYRANGE_RDBEAR_1454284800_1454284800_103.0000_94.0000: 1
EXPIRYMISS_RDBEAR_1454284800_1454284801_103.0000_94.0000: 0
EXPIRYRANGE_RDBEAR_1454284800_1454284800_103.0000_94.0000: 1
CALL_RDBEAR_1454284800_1454284800_0.0001: 1
PUT_RDBEAR_1454284800_1454284800_0.0001: 0
CALL_RDBEAR_1454284800_1454284801_0.0001: 1
PUT_RDBEAR_1454284800_1454284800_0.0001: 0
EXPIRYMISS_RDBULL_1454284800_1454284800_103.0000_94.0000: 0
EXPIRYRANGE_RDBULL_1454284800_1454284800_103.0000_94.0000: 1
EXPIRYMISS_RDBULL_1454284800_1454284801_103.0000_94.0000: 0
EXPIRYRANGE_RDBULL_1454284800_1454284800_103.0000_94.0000: 1
CALL_RDBULL_1454284800_1454284800_0.0001: 1
PUT_RDBULL_1454284800_1454284800_0.0001: 0
CALL_RDBULL_1454284800_1454284801_0.0001: 1
PUT_RDBULL_1454284800_1454284800_0.0001: 0
EXPIRYMISS_R_100_1454284800_1454284800_103.00_94.00: 0
EXPIRYRANGE_R_100_1454284800_1454284800_103.00_94.00: 1
EXPIRYMISS_R_100_1454284800_1454284801_103.00_94.00: 0
EXPIRYRANGE_R_100_1454284800_1454284800_103.00_94.00: 1
CALL_R_100_1454284800_1454284979_101.00: 0
PUT_R_100_1454284800_1454284811_101.00: 1
CALL_R_100_1454284800_1454284800_0.01: 1
PUT_R_100_1454284800_1454284800_0.01: 0
CALL_R_100_1454284800_1454285158_101.00: 0
PUT_R_100_1454284800_1454284823_101.00: 1
CALL_R_100_1454284800_1454284801_0.01: 1
PUT_R_100_1454284800_1454284800_0.01: 0
EXPIRYMISS_R_25_1454284800_1454284800_103.000_94.000: 0
EXPIRYRANGE_R_25_1454284800_1454284800_103.000_94.000: 1
EXPIRYMISS_R_25_1454284800_1454284801_103.000_94.000: 0
EXPIRYRANGE_R_25_1454284800_1454284800_103.000_94.000: 1
PUT_R_25_1454284800_1454284811_100.100: 1
CALL_R_25_1454284800_1454284800_0.001: 1
PUT_R_25_1454284800_1454284800_0.001: 0
PUT_R_25_1454284800_1454284823_100.100: 1
CALL_R_25_1454284800_1454284801_0.001: 1
PUT_R_25_1454284800_1454284800_0.001: 0
RANGE_RDBEAR_1454284800_1454284800_103.0000_94.0000 : 1
UPORDOWN_RDBEAR_1454284800_1454284800_103.0000_94.0000 : 0
RANGE_RDBEAR_1454284800_1454284801_103.0000_94.0000 : 1
UPORDOWN_RDBEAR_1454284800_1454284800_103.0000_94.0000 : 0
ONETOUCH_RDBEAR_1454284800_1454325120_100.0000 : 1
NOTOUCH_RDBEAR_1454284800_1454287488_100.0000 : 0.00087
ONETOUCH_RDBEAR_1454284800_1454284979_100.0100 : 0.56594
NOTOUCH_RDBEAR_1454284800_1454284811_100.0100 : 0.91786
ONETOUCH_RDBEAR_1454284800_1454365440_100.0000 : 1
NOTOUCH_RDBEAR_1454284800_1454290176_100.0000 : 0.00012
ONETOUCH_RDBEAR_1454284800_1454285158_100.0100 : 0.63455
NOTOUCH_RDBEAR_1454284800_1454284823_100.0100 : 0.78793
RANGE_RDBULL_1454284800_1454284800_103.0000_94.0000 : 1
UPORDOWN_RDBULL_1454284800_1454284800_103.0000_94.0000 : 0
RANGE_RDBULL_1454284800_1454284801_103.0000_94.0000 : 1
UPORDOWN_RDBULL_1454284800_1454284800_103.0000_94.0000 : 0
ONETOUCH_RDBULL_1454284800_1454325120_100.0000 : 0.91799
NOTOUCH_RDBULL_1454284800_1454287488_100.0000 : 0.08204
ONETOUCH_RDBULL_1454284800_1454284979_100.0100 : 0.84949
NOTOUCH_RDBULL_1454284800_1454284811_100.0100 : 0.87217
ONETOUCH_RDBULL_1454284800_1454365440_100.0000 : 0.91799
NOTOUCH_RDBULL_1454284800_1454290176_100.0000 : 0.08201
ONETOUCH_RDBULL_1454284800_1454285158_100.0100 : 0.93508
NOTOUCH_RDBULL_1454284800_1454284823_100.0100 : 0.67161
RANGE_R_100_1454284800_1454284800_103.00_94.00 : 1
UPORDOWN_R_100_1454284800_1454284800_103.00_94.00 : 0
RANGE_R_100_1454284800_1454284801_103.00_94.00 : 1
UPORDOWN_R_100_1454284800_1454284800_103.00_94.00 : 0
ONETOUCH_R_100_1454284800_1454325120_100.00 : 0.99673
NOTOUCH_R_100_1454284800_1454287488_100.00 : 0.01267
ONETOUCH_R_100_1454284800_1454284979_101.00 : 0
NOTOUCH_R_100_1454284800_1454284811_101.00 : 1
ONETOUCH_R_100_1454284800_1454365440_100.00 : 0.99769
NOTOUCH_R_100_1454284800_1454290176_100.00 : 0.00896
ONETOUCH_R_100_1454284800_1454285158_101.00 : 0
NOTOUCH_R_100_1454284800_1454284823_101.00 : 1
RANGE_R_25_1454284800_1454284800_103.000_94.000 : 1
UPORDOWN_R_25_1454284800_1454284800_103.000_94.000 : 0
RANGE_R_25_1454284800_1454284801_103.000_94.000 : 1
UPORDOWN_R_25_1454284800_1454284800_103.000_94.000 : 0
ONETOUCH_R_25_1454284800_1454325120_100.000 : 0.99673
NOTOUCH_R_25_1454284800_1454287488_100.000 : 0.01267
ONETOUCH_R_25_1454284800_1454284979_100.100 : 0.00037
NOTOUCH_R_25_1454284800_1454284811_100.100 : 1
ONETOUCH_R_25_1454284800_1454365440_100.000 : 0.99769
NOTOUCH_R_25_1454284800_1454290176_100.000 : 0.00896
ONETOUCH_R_25_1454284800_1454285158_100.100 : 0.01188
NOTOUCH_R_25_1454284800_1454284823_100.100 : 1
RESETCALL_R_100_1454284800_1454325120_100.00: 0.62357
RESETPUT_R_100_1454284800_1454287488_100.00: 0.62605
RESETCALL_R_100_1454284800_1454284979_101.00: 0.62491
RESETPUT_R_100_1454284800_1454284811_101.00: 0.62507
RESETCALL_R_100_1454284800_1454365440_100.00: 0.62298
RESETPUT_R_100_1454284800_1454290176_100.00: 0.62649
RESETCALL_R_100_1454284800_1454285158_101.00: 0.62487
RESETPUT_R_100_1454284800_1454284823_101.00: 0.6251
RESETCALL_R_25_1454284800_1454325120_100.000: 0.62357
RESETPUT_R_25_1454284800_1454287488_100.000: 0.62605
RESETCALL_R_25_1454284800_1454284979_100.100: 0.62491
RESETPUT_R_25_1454284800_1454284811_100.100: 0.62507
RESETCALL_R_25_1454284800_1454365440_100.000: 0.62298
RESETPUT_R_25_1454284800_1454290176_100.000: 0.62649
RESETCALL_R_25_1454284800_1454285158_100.100: 0.62487
RESETPUT_R_25_1454284800_1454284823_100.100: 0.6251
