---
CALL_R_100_10_1474860428_1474860548_S0P_0|1m: 4.88
CALL_R_100_10_1474860428_1474860728_S0P_0|1m: 4.88
CALL_R_100_10_1474860428_1474861028_S0P_0|1m: 4.88
CALL_R_100_10_1474860428_1474867628_S0P_0|1m: 4.88
CALL_R_100_10_1474860428_1474882028_S0P_0|1m: 4.88
CALL_R_25_10_1474860428_1474860548_S0P_0|1m: 4.88
CALL_R_25_10_1474860428_1474860728_S0P_0|1m: 4.88
CALL_R_25_10_1474860428_1474861028_S0P_0|1m: 4.88
CALL_R_25_10_1474860428_1474867628_S0P_0|1m: 4.88
CALL_R_25_10_1474860428_1474882028_S0P_0|1m: 4.88
CALL_frxEURUSD_10_1474860428_1474860548_S0P_0|1m: 5.1
CALL_frxEURUSD_10_1474860428_1474860728_S0P_0|1m: 5.1
CALL_frxEURUSD_10_1474860428_1474861028_S0P_0|1m: 5.1
CALL_frxEURUSD_10_1474860428_1474867628_S0P_0|1m: 5.1
CALL_frxEURUSD_10_1474860428_1474882028_S0P_0|1m: 5
CALL_frxUSDJPY_10_1474860428_1474860548_S0P_0|1m: 5
CALL_frxUSDJPY_10_1474860428_1474860728_S0P_0|1m: 5
CALL_frxUSDJPY_10_1474860428_1474861028_S0P_0|1m: 5
CALL_frxUSDJPY_10_1474860428_1474867628_S0P_0|1m: 5
CALL_frxUSDJPY_10_1474860428_1474882028_S0P_0|1m: 5
CALL_AEX_10_1474860428_1474860548_S0P_0|1m: 4.5
CALL_AEX_10_1474860428_1474860728_S0P_0|1m: 4.5
CALL_AEX_10_1474860428_1474861028_S0P_0|1m: 4.5
CALL_AEX_10_1474860428_1474867628_S0P_0|1m: 4.5
CALL_AEX_10_1474860428_1474882028_S0P_0|1m: 4.5
CALL_frxBROUSD_10_1474860428_1474860548_S0P_0|1m: 4.5
CALL_frxBROUSD_10_1474860428_1474860728_S0P_0|1m: 4.5
CALL_frxBROUSD_10_1474860428_1474861028_S0P_0|1m: 4.5
CALL_frxBROUSD_10_1474860428_1474867628_S0P_0|1m: 4.5
CALL_frxBROUSD_10_1474860428_1474882028_S0P_0|1m: 4.5
CALL_WLDEUR_10_1474860428_1474860548_S0P_0|1m: 4.65
CALL_WLDEUR_10_1474860428_1474860728_S0P_0|1m: 4.65
CALL_WLDEUR_10_1474860428_1474861028_S0P_0|1m: 4.65
CALL_WLDEUR_10_1474860428_1474867628_S0P_0|1m: 4.65
CALL_WLDEUR_10_1474860428_1474882028_S0P_0|1m: 4.65
PUT_R_100_10_1474860428_1474860548_S0P_0|1m: 4.88
PUT_R_100_10_1474860428_1474860728_S0P_0|1m: 4.88
PUT_R_100_10_1474860428_1474861028_S0P_0|1m: 4.88
PUT_R_100_10_1474860428_1474867628_S0P_0|1m: 4.88
PUT_R_100_10_1474860428_1474882028_S0P_0|1m: 4.88
PUT_R_25_10_1474860428_1474860548_S0P_0|1m: 4.88
PUT_R_25_10_1474860428_1474860728_S0P_0|1m: 4.88
PUT_R_25_10_1474860428_1474861028_S0P_0|1m: 4.88
PUT_R_25_10_1474860428_1474867628_S0P_0|1m: 4.88
PUT_R_25_10_1474860428_1474882028_S0P_0|1m: 4.88
PUT_frxEURUSD_10_1474860428_1474860548_S0P_0|1m: 3.65
PUT_frxEURUSD_10_1474860428_1474860728_S0P_0|1m: 3.65
PUT_frxEURUSD_10_1474860428_1474861028_S0P_0|1m: 3.65
PUT_frxEURUSD_10_1474860428_1474867628_S0P_0|1m: 3.65
PUT_frxEURUSD_10_1474860428_1474882028_S0P_0|1m: 3.65
PUT_frxUSDJPY_10_1474860428_1474860548_S0P_0|1m: 3.66
PUT_frxUSDJPY_10_1474860428_1474860728_S0P_0|1m: 3.66
PUT_frxUSDJPY_10_1474860428_1474861028_S0P_0|1m: 3.66
PUT_frxUSDJPY_10_1474860428_1474867628_S0P_0|1m: 3.66
PUT_frxUSDJPY_10_1474860428_1474882028_S0P_0|1m: 3.66
PUT_AEX_10_1474860428_1474860548_S0P_0|1m: 4.5
PUT_AEX_10_1474860428_1474860728_S0P_0|1m: 4.5
PUT_AEX_10_1474860428_1474861028_S0P_0|1m: 4.5
PUT_AEX_10_1474860428_1474867628_S0P_0|1m: 4.5
PUT_AEX_10_1474860428_1474882028_S0P_0|1m: 4.5
PUT_frxBROUSD_10_1474860428_1474860548_S0P_0|1m: 4.5
PUT_frxBROUSD_10_1474860428_1474860728_S0P_0|1m: 4.5
PUT_frxBROUSD_10_1474860428_1474861028_S0P_0|1m: 4.5
PUT_frxBROUSD_10_1474860428_1474867628_S0P_0|1m: 4.5
PUT_frxBROUSD_10_1474860428_1474882028_S0P_0|1m: 4.5
PUT_WLDEUR_10_1474860428_1474860548_S0P_0|1m: 4.65
PUT_WLDEUR_10_1474860428_1474860728_S0P_0|1m: 4.65
PUT_WLDEUR_10_1474860428_1474861028_S0P_0|1m: 4.65
PUT_WLDEUR_10_1474860428_1474867628_S0P_0|1m: 4.65
PUT_WLDEUR_10_1474860428_1474882028_S0P_0|1m: 4.65
CALL_frxEURUSD_10_1474860428_1474860608_S0P_0|3m: 4.55
CALL_frxEURUSD_10_1474860428_1474860728_S0P_0|3m: 5.1
CALL_frxEURUSD_10_1474860428_1474861028_S0P_0|3m: 5.1
CALL_frxEURUSD_10_1474860428_1474867628_S0P_0|3m: 5.1
CALL_frxEURUSD_10_1474860428_1474882028_S0P_0|3m: 5
CALL_frxUSDJPY_10_1474860428_1474860608_S0P_0|3m: 4.65
CALL_frxUSDJPY_10_1474860428_1474860728_S0P_0|3m: 5
CALL_frxUSDJPY_10_1474860428_1474861028_S0P_0|3m: 5
CALL_frxUSDJPY_10_1474860428_1474867628_S0P_0|3m: 5
CALL_frxUSDJPY_10_1474860428_1474882028_S0P_0|3m: 5
CALL_frxBROUSD_10_1474860428_1474860608_S0P_0|3m: 4.5
CALL_frxBROUSD_10_1474860428_1474860728_S0P_0|3m: 4.5
CALL_frxBROUSD_10_1474860428_1474861028_S0P_0|3m: 4.5
CALL_frxBROUSD_10_1474860428_1474867628_S0P_0|3m: 4.5
CALL_frxBROUSD_10_1474860428_1474882028_S0P_0|3m: 4.5
PUT_frxEURUSD_10_1474860428_1474860608_S0P_0|3m: 4.55
PUT_frxEURUSD_10_1474860428_1474860728_S0P_0|3m: 3.66
PUT_frxEURUSD_10_1474860428_1474861028_S0P_0|3m: 3.66
PUT_frxEURUSD_10_1474860428_1474867628_S0P_0|3m: 3.66
PUT_frxEURUSD_10_1474860428_1474882028_S0P_0|3m: 3.65
PUT_frxUSDJPY_10_1474860428_1474860608_S0P_0|3m: 4.65
PUT_frxUSDJPY_10_1474860428_1474860728_S0P_0|3m: 3.66
PUT_frxUSDJPY_10_1474860428_1474861028_S0P_0|3m: 3.66
PUT_frxUSDJPY_10_1474860428_1474867628_S0P_0|3m: 3.66
PUT_frxUSDJPY_10_1474860428_1474882028_S0P_0|3m: 3.66
PUT_frxBROUSD_10_1474860428_1474860608_S0P_0|3m: 4.5
PUT_frxBROUSD_10_1474860428_1474860728_S0P_0|3m: 4.5
PUT_frxBROUSD_10_1474860428_1474861028_S0P_0|3m: 4.5
PUT_frxBROUSD_10_1474860428_1474867628_S0P_0|3m: 4.5
PUT_frxBROUSD_10_1474860428_1474882028_S0P_0|3m: 4.5

