---
CALL_OTC_AEX_1454284800_1454889600_100.07: 0.366986009352123
CALL_OTC_AEX_1454284800_1454889600_100.55: 0.00894540354581158
CALL_OTC_AEX_1454284800_1454889600_101.04: 0.0125476280825583
CALL_OTC_AEX_1454284800_1454889600_99.11: 1
CALL_OTC_AEX_1454284800_1454889600_99.59: 1
CALL_OTC_AEX_1454284800_1455494400_100.14: 0.349983317198804
CALL_OTC_AEX_1454284800_1455494400_100.79: 0.00878650352199486
CALL_OTC_AEX_1454284800_1455494400_101.47: 0.012297164257234
CALL_OTC_AEX_1454284800_1455494400_98.82: 1
CALL_OTC_AEX_1454284800_1455494400_99.48: 1
CALL_WLDEUR_1454284800_1454889600_100.000: 0.516811510165174
CALL_WLDEUR_1454284800_1455494400_100.000: 0.521340569614106
CALL_frxBROUSD_1454284800_1454889600_100.000: 0.501983542459587
CALL_frxBROUSD_1454284800_1455494400_100.000: 0.500593195786989
CALL_frxUSDJPY_1454284800_1454889600_100.246: 0.505231575273394
CALL_frxUSDJPY_1454284800_1454889600_100.517: 0.397717394642117
CALL_frxUSDJPY_1454284800_1454889600_99.435: 0.812616339830303
CALL_frxUSDJPY_1454284800_1454889600_99.709: 0.721005564866061
CALL_frxUSDJPY_1454284800_1454889600_99.978: 0.615476460505474
CALL_frxUSDJPY_1454284800_1455494400_100.332: 0.453337687301026
CALL_frxUSDJPY_1454284800_1455494400_100.713: 0.364960144210082
CALL_frxUSDJPY_1454284800_1455494400_99.195: 0.724188624164686
CALL_frxUSDJPY_1454284800_1455494400_99.580: 0.639641153616292
CALL_frxUSDJPY_1454284800_1455494400_99.957: 0.546718073290105
CALL_frxXAUUSD_1454284800_1454889600_100.02: 0.596623460484939
CALL_frxXAUUSD_1454284800_1454889600_100.29: 0.487966320927106
CALL_frxXAUUSD_1454284800_1454889600_100.55: 0.387277011892041
CALL_frxXAUUSD_1454284800_1454889600_99.49: 0.791879783438957
CALL_frxXAUUSD_1454284800_1454889600_99.76: 0.699117015207245
CALL_frxXAUUSD_1454284800_1455494400_100.04: 0.520274646533234
CALL_frxXAUUSD_1454284800_1455494400_100.41: 0.431018262322109
CALL_frxXAUUSD_1454284800_1455494400_100.78: 0.347791656770074
CALL_frxXAUUSD_1454284800_1455494400_99.31: 0.693735517593653
CALL_frxXAUUSD_1454284800_1455494400_99.68: 0.609581425642133
EXPIRYMISS_OTC_AEX_1454284800_1454889600_105.08_95.31: 0.0363305054923388
EXPIRYMISS_OTC_AEX_1454284800_1454889600_105.08_95.31: 0.0363305054923388
EXPIRYMISS_OTC_AEX_1454284800_1455494400_107.05_93.67: 0.0355758727063408
EXPIRYMISS_OTC_AEX_1454284800_1455494400_107.05_93.67: 0.0355758727063408
EXPIRYMISS_frxUSDJPY_1454284800_1454889600_102.434_96.990: 0.158961676633166
EXPIRYMISS_frxUSDJPY_1454284800_1454889600_102.708_97.382: 0.134706012527797
EXPIRYMISS_frxUSDJPY_1454284800_1455494400_103.279_95.524: 0.196412256453392
EXPIRYMISS_frxUSDJPY_1454284800_1455494400_103.785_96.390: 0.187947181763745
EXPIRYMISS_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.139235300314013
EXPIRYMISS_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.139235300314013
EXPIRYMISS_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.191284824136995
EXPIRYMISS_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.191284824136995
EXPIRYRANGE_OTC_AEX_1454284800_1454889600_105.08_95.31: 1
EXPIRYRANGE_OTC_AEX_1454284800_1454889600_105.08_95.31: 1
EXPIRYRANGE_OTC_AEX_1454284800_1455494400_107.05_93.67: 1
EXPIRYRANGE_OTC_AEX_1454284800_1455494400_107.05_93.67: 1
EXPIRYRANGE_frxUSDJPY_1454284800_1454889600_102.434_96.990: 0.870237667999201
EXPIRYRANGE_frxUSDJPY_1454284800_1454889600_102.708_97.382: 0.89477521194015
EXPIRYRANGE_frxUSDJPY_1454284800_1455494400_103.279_95.524: 0.831536549857268
EXPIRYRANGE_frxUSDJPY_1454284800_1455494400_103.785_96.390: 0.841570197761029
EXPIRYRANGE_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.892393240127034
EXPIRYRANGE_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.892393240127034
EXPIRYRANGE_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.840346166932542
EXPIRYRANGE_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.840346166932542
PUT_OTC_AEX_1454284800_1454889600_100.07: 0.642583922016141
PUT_OTC_AEX_1454284800_1454889600_100.55: 1
PUT_OTC_AEX_1454284800_1454889600_101.04: 1
PUT_OTC_AEX_1454284800_1454889600_99.11: 0.0126116065274601
PUT_OTC_AEX_1454284800_1454889600_99.59: 0.00975390196916683
PUT_OTC_AEX_1454284800_1455494400_100.14: 0.65903829983653
PUT_OTC_AEX_1454284800_1455494400_100.79: 1
PUT_OTC_AEX_1454284800_1455494400_101.47: 1
PUT_OTC_AEX_1454284800_1455494400_98.82: 0.0125710398381212
PUT_OTC_AEX_1454284800_1455494400_99.48: 0.0102973572755183
PUT_WLDEUR_1454284800_1454889600_100.000: 0.492673429674249
PUT_WLDEUR_1454284800_1455494400_100.000: 0.487639582007208
PUT_frxBROUSD_1454284800_1454889600_100.000: 0.507501397379837
PUT_frxBROUSD_1454284800_1455494400_100.000: 0.508386955834325
PUT_frxUSDJPY_1454284800_1454889600_100.246: 0.501325528687072
PUT_frxUSDJPY_1454284800_1454889600_100.517: 0.612040302069978
PUT_frxUSDJPY_1454284800_1454889600_99.435: 0.19923841688383
PUT_frxUSDJPY_1454284800_1454889600_99.709: 0.287728826592059
PUT_frxUSDJPY_1454284800_1454889600_99.978: 0.389915232684182
PUT_frxUSDJPY_1454284800_1455494400_100.332: 0.551009117665044
PUT_frxUSDJPY_1454284800_1455494400_100.713: 0.642732768838543
PUT_frxUSDJPY_1454284800_1455494400_99.195: 0.286482193228153
PUT_frxUSDJPY_1454284800_1455494400_99.580: 0.367804035185118
PUT_frxUSDJPY_1454284800_1455494400_99.957: 0.457288802168254
PUT_frxXAUUSD_1454284800_1454889600_100.02: 0.412885192113479
PUT_frxXAUUSD_1454284800_1454889600_100.29: 0.524859826085658
PUT_frxXAUUSD_1454284800_1454889600_100.55: 0.628611363300102
PUT_frxXAUUSD_1454284800_1454889600_99.49: 0.224152305181134
PUT_frxXAUUSD_1454284800_1454889600_99.76: 0.313658509098685
PUT_frxXAUUSD_1454284800_1455494400_100.04: 0.488723240528677
PUT_frxXAUUSD_1454284800_1455494400_100.41: 0.581341612536134
PUT_frxXAUUSD_1454284800_1455494400_100.78: 0.667767039357867
PUT_frxXAUUSD_1454284800_1455494400_99.31: 0.321913853440524
PUT_frxXAUUSD_1454284800_1455494400_99.68: 0.402758904287674
