---
CALL_OTC_AEX_1454284800_1454889600_100.07: 0.478086982350242
CALL_OTC_AEX_1454284800_1454889600_100.55: 0.466965597458884
CALL_OTC_AEX_1454284800_1454889600_101.04: 0.455501906180607
CALL_OTC_AEX_1454284800_1454889600_99.11: 0.515959910414869
CALL_OTC_AEX_1454284800_1454889600_99.59: 0.49698471152001
CALL_OTC_AEX_1454284800_1455494400_100.14: 0.469330193739115
CALL_OTC_AEX_1454284800_1455494400_100.79: 0.457972221698504
CALL_OTC_AEX_1454284800_1455494400_101.47: 0.446019515867546
CALL_OTC_AEX_1454284800_1455494400_98.82: 0.508042969209502
CALL_OTC_AEX_1454284800_1455494400_99.48: 0.488676127705865
CALL_WLDEUR_1454284800_1454889600_100.000: 0.516811510165174
CALL_WLDEUR_1454284800_1455494400_100.000: 0.521340569614106
CALL_frxBROUSD_1454284800_1454889600_100.00: 0.501983542459587
CALL_frxBROUSD_1454284800_1455494400_100.00: 0.500593195786989
CALL_frxUSDJPY_1454284800_1454889600_100.256: 0.501136078134938
CALL_frxUSDJPY_1454284800_1454889600_100.539: 0.397005156706542
CALL_frxUSDJPY_1454284800_1454889600_99.409: 0.79719942145683
CALL_frxUSDJPY_1454284800_1454889600_99.695: 0.709277713278032
CALL_frxUSDJPY_1454284800_1454889600_99.976: 0.607644113698242
CALL_frxUSDJPY_1454284800_1455494400_100.339: 0.450242939326874
CALL_frxUSDJPY_1454284800_1455494400_100.729: 0.364838630335892
CALL_frxUSDJPY_1454284800_1455494400_99.173: 0.711583983334408
CALL_frxUSDJPY_1454284800_1455494400_99.568: 0.630002454843383
CALL_frxUSDJPY_1454284800_1455494400_99.955: 0.540291604889723
CALL_frxXAUUSD_1454284800_1454889600_100.02: 0.596601326353521
CALL_frxXAUUSD_1454284800_1454889600_100.30: 0.488675912226636
CALL_frxXAUUSD_1454284800_1454889600_100.58: 0.384919065916888
CALL_frxXAUUSD_1454284800_1454889600_99.47: 0.790506738351042
CALL_frxXAUUSD_1454284800_1454889600_99.75: 0.698402425379313
CALL_frxXAUUSD_1454284800_1455494400_100.04: 0.520254229429579
CALL_frxXAUUSD_1454284800_1455494400_100.42: 0.430761177494964
CALL_frxXAUUSD_1454284800_1455494400_100.80: 0.347355742684959
CALL_frxXAUUSD_1454284800_1455494400_99.30: 0.691922188283202
CALL_frxXAUUSD_1454284800_1455494400_99.67: 0.609761473049175
EXPIRYMISS_OTC_AEX_1454284800_1454889600_105.08_95.31: 0.737211205871678
EXPIRYMISS_OTC_AEX_1454284800_1455494400_107.05_93.67: 0.730418560832838
EXPIRYMISS_frxUSDJPY_1454284800_1454889600_102.532_96.837: 0.182463016909523
EXPIRYMISS_frxUSDJPY_1454284800_1454889600_102.829_97.270: 0.159476749999172
EXPIRYMISS_frxUSDJPY_1454284800_1455494400_103.349_95.385: 0.206158118551759
EXPIRYMISS_frxUSDJPY_1454284800_1455494400_103.878_96.306: 0.203398252613201
EXPIRYMISS_frxXAUUSD_1454284800_1454889600_102.86_97.26: 0.139372803785563
EXPIRYMISS_frxXAUUSD_1454284800_1455494400_103.92_96.32: 0.19119194521136
EXPIRYRANGE_OTC_AEX_1454284800_1454889600_105.08_95.31: 0.335058100155486
EXPIRYRANGE_OTC_AEX_1454284800_1455494400_107.05_93.67: 0.33987007915262
EXPIRYRANGE_frxUSDJPY_1454284800_1454889600_102.532_96.837: 0.845423459076716
EXPIRYRANGE_frxUSDJPY_1454284800_1454889600_102.829_97.270: 0.868748221282754
EXPIRYRANGE_frxUSDJPY_1454284800_1455494400_103.349_95.385: 0.820995840417093
EXPIRYRANGE_frxUSDJPY_1454284800_1455494400_103.878_96.306: 0.825406727798168
EXPIRYRANGE_frxXAUUSD_1454284800_1454889600_102.86_97.26: 0.890732565958124
EXPIRYRANGE_frxXAUUSD_1454284800_1455494400_103.92_96.32: 0.839844589823364
PUT_OTC_AEX_1454284800_1454889600_100.07: 0.531513988374113
PUT_OTC_AEX_1454284800_1454889600_100.55: 0.550359349095158
PUT_OTC_AEX_1454284800_1454889600_101.04: 0.569218809033849
PUT_OTC_AEX_1454284800_1454889600_99.11: 0.508834734706208
PUT_OTC_AEX_1454284800_1454889600_99.59: 0.520225055460343
PUT_OTC_AEX_1454284800_1455494400_100.14: 0.539658358436797
PUT_OTC_AEX_1454284800_1455494400_100.79: 0.558480850548206
PUT_OTC_AEX_1454284800_1455494400_101.47: 0.577742486685278
PUT_OTC_AEX_1454284800_1455494400_98.82: 0.516211825867435
PUT_OTC_AEX_1454284800_1455494400_99.48: 0.528056322657734
PUT_WLDEUR_1454284800_1454889600_100.000: 0.492673429674249
PUT_WLDEUR_1454284800_1455494400_100.000: 0.487639582007208
PUT_frxBROUSD_1454284800_1454889600_100.00: 0.507501397379837
PUT_frxBROUSD_1454284800_1455494400_100.00: 0.508386955834325
PUT_frxUSDJPY_1454284800_1454889600_100.256: 0.505082232671864
PUT_frxUSDJPY_1454284800_1454889600_100.539: 0.612283211485808
PUT_frxUSDJPY_1454284800_1454889600_99.409: 0.214182906210787
PUT_frxUSDJPY_1454284800_1454889600_99.695: 0.299117565960818
PUT_frxUSDJPY_1454284800_1454889600_99.976: 0.397547077521053
PUT_frxUSDJPY_1454284800_1455494400_100.339: 0.553943801750366
PUT_frxUSDJPY_1454284800_1455494400_100.729: 0.642616941058898
PUT_frxUSDJPY_1454284800_1455494400_99.173: 0.298861034127894
PUT_frxUSDJPY_1454284800_1455494400_99.568: 0.377288901250086
PUT_frxUSDJPY_1454284800_1455494400_99.955: 0.463634067181331
PUT_frxXAUUSD_1454284800_1454889600_100.02: 0.412928008748277
PUT_frxXAUUSD_1454284800_1454889600_100.30: 0.52396858869952
PUT_frxXAUUSD_1454284800_1454889600_100.58: 0.630750301927345
PUT_frxXAUUSD_1454284800_1454889600_99.47: 0.225239515481873
PUT_frxXAUUSD_1454284800_1454889600_99.75: 0.314241618373531
PUT_frxXAUUSD_1454284800_1455494400_100.04: 0.488760657003236
PUT_frxXAUUSD_1454284800_1455494400_100.42: 0.581514039332438
PUT_frxXAUUSD_1454284800_1455494400_100.80: 0.668053460263703
PUT_frxXAUUSD_1454284800_1455494400_99.30: 0.32353094544561
PUT_frxXAUUSD_1454284800_1455494400_99.67: 0.402531809545098
