---
NOTOUCH_AEX_1454284800_1454889600_100.07: 0.0203631709130718
NOTOUCH_AEX_1454284800_1454889600_100.55: 0.124858782906802
NOTOUCH_AEX_1454284800_1454889600_101.04: 0.229193358129996
NOTOUCH_AEX_1454284800_1454889600_99.11: 0.210938578902963
NOTOUCH_AEX_1454284800_1454889600_99.59: 0.100489115940226
NOTOUCH_AEX_1454284800_1455494400_100.14: 0.0273938930821903
NOTOUCH_AEX_1454284800_1455494400_100.79: 0.130317151665767
NOTOUCH_AEX_1454284800_1455494400_101.47: 0.235367436467861
NOTOUCH_AEX_1454284800_1455494400_98.82: 0.205000045042223
NOTOUCH_AEX_1454284800_1455494400_99.48: 0.0935839825678645
NOTOUCH_frxUSDJPY_1454284800_1454889600_100.256: 0.131948602381193
NOTOUCH_frxUSDJPY_1454284800_1454889600_100.539: 0.27670345067224
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.409: 0.47647051913126
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.695: 0.252486203912059
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.976: 0.0238499572398133
NOTOUCH_frxUSDJPY_1454284800_1455494400_100.339: 0.120362120013981
NOTOUCH_frxUSDJPY_1454284800_1455494400_100.729: 0.255391188826436
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.173: 0.324697443118068
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.568: 0.173310383684801
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.955: 0.0210598320796862
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.02: 0.0147030471247588
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.30: 0.153012398475858
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.58: 0.293640349470638
NOTOUCH_frxXAUUSD_1454284800_1454889600_99.47: 0.401683564785823
NOTOUCH_frxXAUUSD_1454284800_1454889600_99.75: 0.192679628299619
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.04: 0.0190421351877901
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.42: 0.153166691774849
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.80: 0.285500138910586
NOTOUCH_frxXAUUSD_1454284800_1455494400_99.30: 0.268234024729595
NOTOUCH_frxXAUUSD_1454284800_1455494400_99.67: 0.129163232799206
ONETOUCH_AEX_1454284800_1454889600_100.07: 0.991899326522091
ONETOUCH_AEX_1454284800_1454889600_100.55: 0.902834755634039
ONETOUCH_AEX_1454284800_1454889600_101.04: 0.813231896043481
ONETOUCH_AEX_1454284800_1454889600_99.11: 0.827379272445237
ONETOUCH_AEX_1454284800_1454889600_99.59: 0.922779069338764
ONETOUCH_AEX_1454284800_1455494400_100.14: 0.985784261374411
ONETOUCH_AEX_1454284800_1455494400_100.79: 0.897595437839516
ONETOUCH_AEX_1454284800_1455494400_101.47: 0.806901677927824
ONETOUCH_AEX_1454284800_1455494400_98.82: 0.83210096060966
ONETOUCH_AEX_1454284800_1455494400_99.48: 0.928562369434701
ONETOUCH_frxUSDJPY_1454284800_1454889600_100.256: 0.882590570221464
ONETOUCH_frxUSDJPY_1454284800_1454889600_100.539: 0.743612100738658
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.409: 0.546169915476542
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.695: 0.764060069730884
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.976: 0.98618745546636
ONETOUCH_frxUSDJPY_1454284800_1455494400_100.339: 0.891651247975612
ONETOUCH_frxUSDJPY_1454284800_1455494400_100.729: 0.762569959581486
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.173: 0.696511383379261
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.568: 0.841382566323057
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.955: 0.986680583720569
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.02: 0.995661539562076
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.30: 0.863664164811785
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.58: 0.72899424171209
ONETOUCH_frxXAUUSD_1454284800_1454889600_99.47: 0.620086914320435
ONETOUCH_frxXAUUSD_1454284800_1454889600_99.75: 0.823038400173498
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.04: 0.991601382281937
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.42: 0.863921071824994
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.80: 0.737665328708391
ONETOUCH_frxXAUUSD_1454284800_1455494400_99.30: 0.753580444398541
ONETOUCH_frxXAUUSD_1454284800_1455494400_99.67: 0.886515959660776
RANGE_AEX_1454284800_1454889600_105.08_95.31: 0.672477062355095
RANGE_AEX_1454284800_1455494400_107.05_93.67: 0.670751377114666
RANGE_frxUSDJPY_1454284800_1454889600_102.532_96.837: 0.715651180404143
RANGE_frxUSDJPY_1454284800_1454889600_102.829_97.270: 0.782910873091811
RANGE_frxUSDJPY_1454284800_1455494400_103.349_95.385: 0.683478696873146
RANGE_frxUSDJPY_1454284800_1455494400_103.878_96.306: 0.707982763747904
RANGE_frxXAUUSD_1454284800_1454889600_102.86_97.26: 0.771941594329618
RANGE_frxXAUUSD_1454284800_1455494400_103.92_96.32: 0.707220327676446
UPORDOWN_AEX_1454284800_1454889600_105.08_95.31: 0.470833119655403
UPORDOWN_AEX_1454284800_1455494400_107.05_93.67: 0.469306491791286
UPORDOWN_frxUSDJPY_1454284800_1454889600_102.532_96.837: 0.340626042575241
UPORDOWN_frxUSDJPY_1454284800_1454889600_102.829_97.270: 0.27393824094162
UPORDOWN_frxUSDJPY_1454284800_1455494400_103.349_95.385: 0.372038721484256
UPORDOWN_frxUSDJPY_1454284800_1455494400_103.878_96.306: 0.350613317029789
UPORDOWN_frxXAUUSD_1454284800_1454889600_102.86_97.26: 0.287696911044007
UPORDOWN_frxXAUUSD_1454284800_1455494400_103.92_96.32: 0.35484656285517
