---
NOTOUCH_AEX_1454284800_1454889600_100.07: 0.0187372987794579
NOTOUCH_AEX_1454284800_1454889600_100.55: 0.12017141130197
NOTOUCH_AEX_1454284800_1454889600_101.04: 0.222037630226832
NOTOUCH_AEX_1454284800_1454889600_99.11: 0.217969014041077
NOTOUCH_AEX_1454284800_1454889600_99.59: 0.10454723337749
NOTOUCH_AEX_1454284800_1455494400_100.14: 0.0254842622423562
NOTOUCH_AEX_1454284800_1455494400_100.79: 0.125158715130037
NOTOUCH_AEX_1454284800_1455494400_101.47: 0.227565577048789
NOTOUCH_AEX_1454284800_1455494400_98.82: 0.212502166838766
NOTOUCH_AEX_1454284800_1455494400_99.48: 0.0977508715096957
NOTOUCH_frxUSDJPY_1454284800_1454889600_100.247: 0.0812331607551027
NOTOUCH_frxUSDJPY_1454284800_1454889600_100.521: 0.21217800865816
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.431: 0.540296034690375
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.707: 0.251262952381875
NOTOUCH_frxUSDJPY_1454284800_1454889600_99.978: 0.0209410291010395
NOTOUCH_frxUSDJPY_1454284800_1455494400_100.333: 0.100401889289305
NOTOUCH_frxUSDJPY_1454284800_1455494400_100.715: 0.231354220708239
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.191: 0.313845244543213
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.578: 0.152772625177935
NOTOUCH_frxUSDJPY_1454284800_1455494400_99.957: 0.0171550008588758
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.02: 0.00867714420068725
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.29: 0.0962566967145608
NOTOUCH_frxXAUUSD_1454284800_1454889600_100.55: 0.223908331826501
NOTOUCH_frxXAUUSD_1454284800_1454889600_99.49: 0.452592544747773
NOTOUCH_frxXAUUSD_1454284800_1454889600_99.76: 0.192181041031221
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.04: 0.0155458633897634
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.41: 0.12763445943973
NOTOUCH_frxXAUUSD_1454284800_1455494400_100.78: 0.259332720957098
NOTOUCH_frxXAUUSD_1454284800_1455494400_99.31: 0.25858254939008
NOTOUCH_frxXAUUSD_1454284800_1455494400_99.68: 0.113275003162811
ONETOUCH_AEX_1454284800_1454889600_100.07: 0.990142764133219
ONETOUCH_AEX_1454284800_1454889600_100.55: 0.904953369278134
ONETOUCH_AEX_1454284800_1454889600_101.04: 0.818655349131428
ONETOUCH_AEX_1454284800_1454889600_99.11: 0.822376594814975
ONETOUCH_AEX_1454284800_1454889600_99.59: 0.921546841005831
ONETOUCH_AEX_1454284800_1455494400_100.14: 0.984291499417412
ONETOUCH_AEX_1454284800_1455494400_100.79: 0.900165853015185
ONETOUCH_AEX_1454284800_1455494400_101.47: 0.812992486806376
ONETOUCH_AEX_1454284800_1455494400_98.82: 0.826775388677751
ONETOUCH_AEX_1454284800_1455494400_99.48: 0.92739911479626
ONETOUCH_frxUSDJPY_1454284800_1454889600_100.247: 0.932869965394147
ONETOUCH_frxUSDJPY_1454284800_1454889600_100.521: 0.809157946635267
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.431: 0.486447942987271
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.707: 0.769483830202939
ONETOUCH_frxUSDJPY_1454284800_1454889600_99.978: 0.992491518414524
ONETOUCH_frxUSDJPY_1454284800_1455494400_100.333: 0.912208845445522
ONETOUCH_frxUSDJPY_1454284800_1455494400_100.715: 0.78774664001767
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.191: 0.709043137135994
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.578: 0.863352986384503
ONETOUCH_frxUSDJPY_1454284800_1455494400_99.957: 0.991246682151799
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.02: 0.998854760266839
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.29: 0.919784921652442
ONETOUCH_frxXAUUSD_1454284800_1454889600_100.55: 0.79929993029763
ONETOUCH_frxXAUUSD_1454284800_1454889600_99.49: 0.57314182874929
ONETOUCH_frxXAUUSD_1454284800_1454889600_99.76: 0.827377547814699
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.04: 0.994608749194068
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.41: 0.889916907260337
ONETOUCH_frxXAUUSD_1454284800_1455494400_100.78: 0.764812499852289
ONETOUCH_frxXAUUSD_1454284800_1455494400_99.31: 0.764985055368673
ONETOUCH_frxXAUUSD_1454284800_1455494400_99.68: 0.903667240550947
RANGE_AEX_1454284800_1454889600_105.08_95.31: 0.672478207246225
RANGE_AEX_1454284800_1455494400_107.05_93.67: 0.670758808567997
RANGE_frxUSDJPY_1454284800_1454889600_102.450_96.967: 0.718928073556414
RANGE_frxUSDJPY_1454284800_1454889600_102.727_97.365: 0.781182250391106
RANGE_frxUSDJPY_1454284800_1455494400_103.290_95.503: 0.684691611225253
RANGE_frxUSDJPY_1454284800_1455494400_103.799_96.377: 0.708359490861074
RANGE_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.775184471894886
RANGE_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.708077825773826
UPORDOWN_AEX_1454284800_1454889600_105.08_95.31: 0.470825673846398
UPORDOWN_AEX_1454284800_1455494400_107.05_93.67: 0.469310833414265
UPORDOWN_frxUSDJPY_1454284800_1454889600_102.450_96.967: 0.339538010837599
UPORDOWN_frxUSDJPY_1454284800_1454889600_102.727_97.365: 0.277762549408702
UPORDOWN_frxUSDJPY_1454284800_1455494400_103.290_95.503: 0.372158948159177
UPORDOWN_frxUSDJPY_1454284800_1455494400_103.799_96.377: 0.351434276599974
UPORDOWN_frxXAUUSD_1454284800_1454889600_102.74_97.38: 0.287481521817591
UPORDOWN_frxXAUUSD_1454284800_1455494400_103.82_96.40: 0.355173030909979
