virtual_buy_transaction:
    1m:  20
    1h: 750
virtual_sell_transaction:
    1m:  20
    1h: 750
virtual_batch_sell:
    1m:  10                 # Excessive use of this service indicates an attempt to stay "at the limit"
    1h: 300
websocket_call:
    1m:  240
    1h: 14400
websocket_call_expensive:
    1m: 20
    1h: 1200
websocket_call_pricing:
    1m: 60
    1h: 3600
websocket_call_email:
    1m: 3
    1h: 180
websocket_real_pricing:
    1m: 240
    1h: 14400
websocket_reality_check:
    2m: 1
    1h: 30
