---
callput:
    display_order: 1
    display_name: "Up/Down"
    allow_forward_starting: 1
    supported_expiries:
      - intraday
      - daily
      - tick
    supported_start_types:
      - spot
      - forward
    explanation: "Predict the ending market level relative to a chosen barrier."
    available_types:
      - BOM::Product::Contract::Call
      - BOM::Product::Contract::Put
      - BOM::Product::Contract::Calle
      - BOM::Product::Contract::Pute
touchnotouch:
    display_order: 2
    display_name: "Touch/No Touch"
    is_path_dependent: 1
    supported_expiries:
      - intraday
      - daily
    explanation: "Predict whether or not the market will touch a chosen level before expiration."
    available_types:
      - BOM::Product::Contract::Onetouch
      - BOM::Product::Contract::Notouch
endsinout:
    display_order : 3
    two_barriers: 1
    display_name: "Ends In/Out"
    supported_expiries:
      - intraday
      - daily
    explanation: "Predict the ending market level relative to 2 chosen barriers."
    available_types:
      - BOM::Product::Contract::Expirymiss
      - BOM::Product::Contract::Expiryrange
      - BOM::Product::Contract::Expirymisse
      - BOM::Product::Contract::Expiryrangee
staysinout:
    display_order : 4
    two_barriers: 1
    display_name: "Stays In/Goes Out"
    is_path_dependent: 1
    supported_expiries:
      - intraday
      - daily
    explanation: "Predict whether or not the market will touch either of 2 chosen levels before expiration."
    available_types:
      - BOM::Product::Contract::Range
      - BOM::Product::Contract::Upordown
digits:
    display_order : 5
    display_name: "Digits"
    supported_expiries:
      - tick
    explanation: "Predict the last digit of the market price at expiration."
    available_types:
      - BOM::Product::Contract::Digitmatch
      - BOM::Product::Contract::Digitdiff
      - BOM::Product::Contract::Digitodd
      - BOM::Product::Contract::Digiteven
      - BOM::Product::Contract::Digitover
      - BOM::Product::Contract::Digitunder
asian:
    display_order: 6
    display_name: "Asians"
    supported_expiries:
      - tick
    explanation: "Predict the ending market level relative to the average market prices throughout the course of the contract"
    available_types:
      - BOM::Product::Contract::Asianu
      - BOM::Product::Contract::Asiand
spreads:
    display_order: 7
    display_name: "Spreads"
    explanation: ""
    available_types:
      - BOM::Product::Contract::Spreadu
      - BOM::Product::Contract::Spreadd
vanilla:
    offer: 0
    display_order: 0
    display_name: "Vanilla Options"
    supported_expiries:
      - intraday
      - daily
      - tick
    available_types:
      - BOM::Product::Contract::Vanilla_call
      - BOM::Product::Contract::Vanilla_put
    explanation: "Plain vanilla options"
