---
DFMGI: 0.1
FTAW01: 0.1
ISEQ: 0.1
JCI: 0.1
RDBEAR: 1.55
RDBULL: 1.75
RDYANG: 1.75
RDYIN: 1.55
R_100: 1
R_25: 0.25
R_50: 0.5
R_75: 0.75
SASEIDX: 0.1
SGES: 0.1
SGFS: 0.1
SGH: 0.1
SGI: 0.1
SGM: 0.1
SGN: 0.1
SGT: 0.1
SGU: 0.1
SPBMGUU: 0.1
SPGSAM: 0.1
SPGSBF: 0.1
SPGSBO: 0.1
SPGSBR: 0.1
SPGSCC: 0.1
SPGSCN: 0.1
SPGSCR: 0.1
SPGSCT: 0.1
SPGSEN: 0.1
SPGSGO: 0.1
SPGSGR: 0.1
SPGSHO: 0.1
SPGSIC: 0.1
SPGSIK: 0.1
SPGSIL: 0.1
SPGSIZ: 0.1
SPGSKC: 0.1
SPGSKW: 0.1
SPGSNG: 0.1
SPGSPT: 0.1
SPGSSB: 0.1
SPGSSO: 0.1
SPGSWT: 0.1
SPGTECOL: 0.1
SPGTIND: 0.1
SPGTNE: 0.1
SPSIAD: 0.1
SPSIBC: 0.1
SPSIBI: 0.1
SPSIBK: 0.1
SPSICH: 0.1
SPSICS: 0.1
SPSIINS: 0.1
SPSILT: 0.1
SPSIMF: 0.1
SPSIPH: 0.1
SPSIRE: 0.1
SPSISC: 0.1
SPSITN: 0.1
SREITGUP: 0.1
WLDAUD: 0.1
WLDEUR: 0.1
WLDGBP: 0.1
WLDUSD: 0.1
frxAUDAED: 0.1
frxAUDTRY: 0.1
frxAUDSAR: 0.1
frxBROAUD: 0.1
frxBROEUR: 0.1
frxBROGBP: 0.1
frxBROUSD: 0.1
frxEURAED: 0.1
frxEURSAR: 0.1
frxGBPAED: 0.1
frxGBPSAR: 0.1
frxUSDAED: 0.1
frxUSDSAR: 0.1
frxXPDAUD: 0.1
frxXPTAUD: 0.1
frxAUDILS: 0.1
frxBTCEUR: 0.1
frxBTCUSD: 0.1
frxEURRUB: 0.1
frxGBPILS: 0.1
frxGBPTRY: 0.1
frxUSDILS: 0.1
frxUSDRUB: 0.1
frxUSDTRY: 0.1
frxCADCHF: 0.1
frxCADJPY: 0.1
frxCHFJPY: 0.1
frxEURTRY: 0.1
frxNZDCHF: 0.1
