---
# Japan specific offerings.
frxAUDJPY: &japan_fx
  callput:
    daily:
      spot:
        euro_non_atm: &day_to_year
          max: 365d
          min: 1d
    intraday:
      spot:
        euro_non_atm: &intraday_historical
          historical_pricer_max: 24h
          historical_pricer_min: 2m
          max: 24h
          min: 2m
  endsinout:
    daily:
      spot:
        euro_non_atm: *day_to_year
    intraday:
      spot:
        euro_non_atm: &intraday
          max: 24h
          min: 2m
  staysinout:
    daily:
      spot:
        american: *day_to_year
    intraday:
      spot:
        american: *intraday
  touchnotouch:
    daily:
      spot:
        american: *day_to_year
    intraday:
      spot:
        american: *intraday_historical
frxAUDUSD: *japan_fx
frxEURGBP: *japan_fx
frxEURJPY: *japan_fx
frxEURUSD: *japan_fx
frxGBPJPY: *japan_fx
frxGBPUSD: *japan_fx
frxUSDCAD: *japan_fx
frxUSDJPY: *japan_fx
