---
# Our daily ohlc is populated by bom_trigger_ohlc_aggregation.pl at 00GMT of next day.
# To allow OTC index and stocks to settle early , db team had come out with a script (bin/bom_ohlc_daily_agg.pl) that will populate them at as as market closed.(cron is cron running on minute 10, 40 of every hour). However, in this cron, they will only be able to insert those ohlc to db with official=true flag.
# So for those OTC index and stocks , they are mark as use_official_ohlc although they are not really use official ohlc from bloomberg or exchange.
random_index:
    name: random_index
    display_name: "Continuous Indices"
    display_order: 1
    is_OTC: 1
    market: volidx
    explanation: 'Associated with a number that represents the relative volatility of the market. For example, the Volatility 100 Index is twice as volatile as the Volatility 50 Index.'
    always_available: 1
random_daily:
    name: random_daily
    display_name: "Daily Reset Indices"
    display_order: 2
    intradays_must_be_same_day: 1
    resets_at_open: 1
    is_OTC: 1
    market: volidx
    explanation: 'Represent a single day of trading with different market factors. They are reset at the start of each trading day (00:00GMT).'
    sod_blackout_start: '1m'
    eod_blackout_expiry: '59s'
random_nightly:
    name: random_nightly
    display_name: "Nocturnes"
    display_order: 3
    intradays_must_be_same_day: 1
    resets_at_open: 1
    is_OTC: 1
    market: volidx
    explanation: 'Represent a single day of trading with different market factors. They are reset at the start of each trading day (12:00GMT).'
    sod_blackout_start: '1m'
    eod_blackout_expiry: '59s'
asia_oceania:
    name: asia_oceania
    display_name: "Asia/Oceania"
    display_order: 1
    market: indices
europe_africa:
    name: europe_africa
    display_name: "Europe/Africa"
    display_order: 2
    market: indices
americas:
    name: americas
    display_name: "Americas"
    display_order: 3
    market: indices
smart_index:
    name: smart_index
    display_name: 'Smart Indices'
    display_order: 4
    asset_type: 'index'
    is_OTC: 1
    market: indices
    explanation: 'Smart Indices'
    volatility_surface_type: "moneyness"
    official_ohlc: 0
middle_east:
    name: middle_east
    display_name: 'Middle East'
    display_order: 5
    market: indices
    volatility_surface_type: "flat"
otc_index:
    name: otc_index
    display_name: 'OTC Indices'
    display_order: 6
    asset_type: 'index'
    market: indices
    is_OTC: 1
    explanation: 'OTC Indices'
    volatility_surface_type: "moneyness"
major_pairs:
    name: major_pairs
    display_name: "Major Pairs"
    display_order: 1
    market: forex
    is_OTC: 1
    explanation: 'The most widely traded and liquid forex pairs.'
    base_commission: 0.025
    risk_profile: 'medium_risk'
minor_pairs:
    name: minor_pairs
    display_name: "Minor Pairs"
    display_order: 2
    is_OTC: 1
    market: forex
    explanation: 'Forex pairs of interest, but with less liquid international markets.'
    base_commission: 0.05
    risk_profile: 'high_risk'
smart_fx:
    name: smart_fx
    display_name: 'Smart FX'
    volatility_surface_type: "flat"
    display_order: 3
    market: forex
    is_OTC: 1
    asset_type: 'currency'
    explanation: 'Smart FX indices'
    base_commission: 0.025
    risk_profile: 'high_risk'
metals:
    name: metals
    display_name: "Metals"
    is_OTC: 1
    display_order: 1
    market: commodities
energy:
    name: energy
    display_name: "Energy"
    display_order: 2
    is_OTC: 1
    market: commodities
    eod_blackout_expiry: '1m'
australia:
    name: australia
    offered: 0
    display_name: "Australia Stocks"
    display_order: 12
    market: stocks
belgium:
    name: belgium
    display_name: "Belgian Stocks"
    offered: 0
    display_order: 11
    market: stocks
amsterdam:
    name: amsterdam
    offered: 0
    display_name: "Dutch Stocks"
    display_order: 10
    market: stocks
france:
    name: france
    offered: 0
    display_name: "French Stocks"
    display_order: 9
    market: stocks
germany:
    name: germany
    offered: 0
    display_name: "Germany Stocks"
    display_order: 5
    market: stocks
india:
    name: india
    offered: 0
    display_name: "India Stocks"
    display_order: 6
    market: stocks
uk:
    name: uk
    offered: 0
    display_name: "United Kingdom Stocks"
    display_order: 7
    market: stocks
us:
    name: us
    offered: 0
    display_name: "United States Stocks"
    display_order: 8
    market: stocks
us_otc_stock:
    name: us_otc_stock
    display_name: 'US'
    display_order: 5
    is_OTC: 1
    asset_type: 'stock'
    market: stocks
    explanation: 'US OTC Stocks'
    volatility_surface_type: "moneyness"
uk_otc_stock:
    name: uk_otc_stock
    display_name: 'UK'
    is_OTC: 1
    display_order: 4
    asset_type: 'stock'
    market: stocks
    explanation: 'UK OTC Stocks'
    volatility_surface_type: "moneyness"   
au_otc_stock:
    name: au_otc_stock
    display_name: 'Australia'
    is_OTC: 1
    display_order: 1
    asset_type: 'stock'
    market: stocks
    explanation: 'Australia OTC Stocks'
    volatility_surface_type: "moneyness"
india_otc_stock:
    name: india_otc_stock
    display_name: 'India'
    is_OTC: 1
    display_order: 3
    asset_type: 'stock'
    market: stocks
    explanation: 'India OTC Stocks'
    volatility_surface_type: "moneyness"
ge_otc_stock:
    name: ge_otc_stock
    display_name: 'Germany'
    is_OTC: 1
    display_order: 2
    asset_type: 'stock'
    market: stocks
    explanation: 'Germany OTC Stocks'
    volatility_surface_type: "moneyness"
asia_oceania_future:
    name: asia_oceania_future
    display_name: "Asia/Oceania Future"
    display_order: 1
    market: futures
europe_africa_future:
    name: europe_africa_future
    display_name: "Europe/Africa Future"
    display_order: 2
    market: futures
americas_future:
    name: americas_future
    display_name: "Americas Future"
    display_order: 3
    market: futures
synthetic_index:
    name: synthetic_index
    display_name: 'Synthetic Index'
    is_OTC: 1
    display_order: 11
    asset_type: 'index'
    market: synthetic
    explanation: 'Synthetic Indices'
#This is just a fake submarket to default to when not defined.
config:
    name: config
    market: config
    display_order: -1
    display_name: "config-only"
