---
system:
  on_qa: 1
  alerts:
    default_recipient: qa-alerts@regentmarkets.com
    email_subject_prefix: "[QA SERVER _HOST_] "
    quants: qa-alerts@regentmarkets.com
    sysadmins: qa-alerts@regentmarkets.com
  send_email_to_clients: 0
price_streamer:
  workers: 2
cgi:
  cookie_secret: Qo5HRXtlp5R3uAWs5qCDkQHyEbazUhBUvEY2YC6tHt4wsLXui9aZFiEnpPUXwmP1
tick_streamer:
  workers: 2
marketing:
  email: qa-alerts@regentmarkets.com
  myaffiliates_email: qa-alerts@regentmarkets.com
compliance:
  email: qa-alerts@regentmarkets.com
accounting:
  email: qa-alerts@regentmarkets.com
tech:
  email: qa-alerts@regentmarkets.com
