---
cgi:
  description: |
    This section contains various parameters that determine behavior of code in cgi.
    DO NOT USE any of these parameters in the /lib modules!!!
  isa: section
  contains:
    cookie_name:
      description: "Cookie names used"
      isa: section
      contains:
        settings:
          description: "Contains all ui settings for the current session"
          isa: Str
          default: "settings"
        login:
          description: "Main login cookie"
          isa: Str
          default: "login"
        login_bo:
          description: "Backoffice login cookie"
          isa: Str
          default: "staff"
    allowed_languages:
      description: "Allowed languages for this website"
      isa: ArrayRef
      default:
        - EN
        - RU
        - ID
      global: 1
    supported_languages:
      description: "Contains all the languages supported, contains both disabled or enabled"
      isa: ArrayRef
      default:
        - EN
        - ID
        - RU
        - ES
        - FR
        - IT
        - PT
        - PL
        - DE
        - JA
        - ZH_CN
        - VI
        - ZH_TW
        - TH
    rtl_languages:
      description: "Contains languages that need right to left support"
      isa: ArrayRef
      default:
        - AR
    backoffice:
      description: "Contains backoffice static url"
      isa: section
      contains:
        static_url:
          description: "Static url of backoffice statics"
          isa: Str
          default: "https://regentmarkets.github.io/binary-static-backoffice/"
          global: 1
    terms_conditions_version:
      description: "Current version for terms and conditions. Use format - Version 35 2015-01-19"
      isa: Str
      default: ""
      global: 1
payments:
  description: "Control parameters for cashier and other payment systems"
  isa: section
  contains:
    payment_limits:
      description: 'Staff limit for payment'
      isa: json_string
      default: '{"jy":"99999"}'
      global: 1
quants:
  description: "Various quants' parameters"
  isa: section
  contains:
    commission:
      description: "Tunable factors for commissions"
      isa: section
      contains:
        adjustment:
          description: "BOM specific adjustments to manage risk."
          isa: section
          contains:
            per_market_scaling:
              description: "The per-market scaling factor for all commissions. (percent of commission)"
              isa: section
              contains:
                forex:
                  description: "The scaling factor for all forex commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1
                indices:
                  description: "The scaling factor for all indices commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1
                commodities:
                  description: "The scaling factor for all commodities commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1
                stocks:
                  description: "The scaling factor for all stocks commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1
                volidx:
                  description: "The scaling factor for all volatility index commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1
                config:
                  description: "The scaling factor for all fake config market commissions. (percent of base commission. Example: Base commission is 3.5%, when you input 100%, the commission charge will be 3.5%. If you input 50%, the commission charge will only be 1.75%.)"
                  isa: Num
                  default: 100
                  global: 1

            global_scaling:
              description: "The scaling factor for all commissions. (percent of commission)"
              isa: Num
              default: 100
              global: 1
    features:
      description: "Toggles for various platform features"
      isa: section
      contains:
        suspend_contract_types:
          description: "Suspend trades only on these bet types (Flash, DoubleDown, DoubleUp, ..)"
          isa: ArrayRef
          default: []
          global: 1
    markets:
      description: "Market-specific variables"
      isa: section
      contains:
        disabled:
          description: "Switch off a given market (volatility index)"
          isa: ArrayRef
          default: []
          global: 1
    underlyings:
      description: "Underlying-specific variables"
      isa: section
      contains:
        disabled_due_to_corporate_actions:
          description: "An array reference of disabled underlying(s) due to corporate actions, e.g.: UKAAL,UKHSBA"
          isa: ArrayRef
          default: []
          global: 1
        disable_autoupdate_vol:
          description: "Disable autoupdate volatility for the following underlyings, eg: frxGBPUSD"
          isa: ArrayRef
          default: []
          global: 1
        suspend_trades:
          description: "A list of underlyings for which trades should be suspended"
          global: 1
          isa: ArrayRef
          default: []
        suspend_buy:
          description: "A list of underlyings for which purchase trades should be suspended"
          global: 1
          isa: ArrayRef
          default: []
    spreads_daily_profit_limit:
      description: "Limit of daily profit for spreads"
      isa: Str
      global: 1
      default: 'extreme_risk'
    custom_client_profiles:
      description: "Custom client limits specification."
      isa: json_string
      global: 1
      default: '{}'
    custom_product_profiles:
      description: "Custom limits specification."
      isa: json_string
      global: 1
      default: '{}'
system:
  description: "Various parameters determining core application functionality"
  isa: section
  contains:
    suspend:
      description: "Suspend one or more of our services"
      isa: section
      contains:
        trading:
          description: "Suspend buy or sell of all trades"
          isa: Bool
          default: 0
          global: 1
        payments:
          description: "Suspend all payments (withdrawal and deposit), including payment agents"
          isa: Bool
          default: 0
          global: 1
        payment_agents:
          description: "Suspend all payments agent transfers"
          isa: Bool
          default: 0
          global: 1
        new_accounts:
          description: "Suspend opening new accounts"
          isa: Bool
          default: 0
          global: 1
        all_logins:
          description: "Suspend all logins to the system"
          isa: Bool
          default: 0
          global: 1
        logins:
          description: "Suspend logins for a broker code (ex. VRTC,MX,CR)"
          isa: ArrayRef
          default: []
          global: 1
        system:
          description: "Suspend viewing any page in the system"
          isa: Bool
          default: 0
          global: 1
        mt5:
          description: "Suspend MT5 API calls"
          isa: Bool
          default: 0
          global: 1
    directory:
      description: "Configuration for system wide directories"
      isa: section
      contains:
        db:
          description: "Directory where we store legacy db stuff, primarily customer documents"
          isa: Str
          default: "/db"
        feed:
          description: "Directory where our feed files are stored"
          isa: Str
          default: "/feed"
          global: 1
        tmp_gif:
          description: "Directory where we store temporary gif files"
          isa: Str
          default: "/home/website/www/temp"
        tmp:
          description: "Temp directory for website operation"
          isa: Str
          default: "/home/tmpramdrive"
    desk_com:
      description: "All configuration related to the Desk.com API"
      isa: section
      contains:
        desk_url:
          description: "Desk.com URL to post info"
          isa: Str
          default: "https://binary.desk.com/api/v2/"
        account_username:
          description: "Username for Desk.com account"
          isa: Str
          default: joanna@regentmarkets.com
        account_password:
          description: "Password for Desk.com account"
          isa: Str
          default: R3kU3rsM5WH7
