maximum_daily_turnover:
  USD: 500000
  EUR: 500000
  AUD: 500000
  GBP: 500000
  JPY: 500000
  BTC: 10
  BCH: 100
  ETH: 100
  LTC: 500
  ETC: 500
max_balance:
  virtual:
    USD: 1000000
    EUR: 1000000
    AUD: 1000000
    GBP: 1000000
    JPY: 100000000
    BTC: 50
    BCH: 50
    ETH: 200
    LTC: 1000
    ETC: 1000
  real:
    USD: 300000
    EUR: 300000
    AUD: 300000
    GBP: 300000
    JPY: 30000000
    BTC: 50
    BCH: 100
    ETH: 100
    LTC: 500
    ETC: 500
max_payout_open_positions:
    USD: 50000
    EUR: 50000
    AUD: 50000
    GBP: 50000
    JPY: 500000
    BTC: 1
    BCH: 10
    ETH: 10
    LTC: 50
    ETC: 50
max_open_bets_default: 60
