virtual_buy_transaction:
    1m: 20
    1h: 750
virtual_sell_transaction:
    1m: 20
    1h: 750
virtual_batch_sell:
    1m: 10
    1h: 300
websocket_call:
    1m: 5280
    1h: 316800
websocket_call_expensive:
    1m: 1320
    1h: 79200
websocket_call_pricing:
    1m: 1320
    1h: 79200
websocket_call_email:
    1m: 3
    1h: 180
websocket_real_pricing:
    1m: 5280
    1h: 316800
