durations:
  - 3h step 4m
  - 1h step 2m
  - 5m step 10s
  - 1m step 5s
  - 10t step 2t
  - 5t step 1t
underlyings:
  - R_50
  - frxUSDJPY
  - frxEURUSD
  - OTC_GDAXI
types:
  - CALL
  - PUT
  - CALLE
