BTC:
    withdrawal:
        timeout: "3d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0
    decimal_places: 8
LTC:
    withdrawal:
        timeout: "3d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0
    decimal_places: 8
BCH:
    withdrawal:
        timeout: "3d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0
    decimal_places: 8
ETH:
    withdrawal:
        timeout: "5d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0
    decimal_places: 18
UST:
    withdrawal:
        timeout: "3d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0.00000546
    decimal_places: 8
USB:
    withdrawal:
        timeout: "3d"
    confirmation:
        required_confirmations: 3
    protocol_cost: 0
    decimal_places: 18
