---
intraday_historical:
  ask_probability:
    bs_probability: 0.477038914004955
    commission_markup: 0.035
    intraday_delta_correction: 0.00828448554641108
    intraday_vega_correction: 0.00162296060969017
    risk_markup: 0.01
  bs_probability:
    K: 79.820
    S: 79.817
    discount_rate: 0
    mu: 0
    payout: 1000
    t: 2.85388127853881e-05
    vol: 0.122873909065588
  commission_markup:
    base_commission: 0.035
    commission_multiplier: 1
  contract_details:
    ccy: JPY
    description: Win payout if USD/JPY is higher than or equal to entry spot plus  3 pips at 15 minutes after contract start time.
    loginID: NA
    order_price: 520
    order_type: buy
    payout: 1000
    ref_spot: NA
    ref_vol: NA
    ref_vol2: NA
    short_code: CALLE_FRXUSDJPY_1000_1352345145_1352346045_S3P_0
    slippage_price: NA
    tick_before_trade_time: 79.817
    trade_ask_price: NA
    trade_bid_price: NA
    trade_time: 2012-11-08 03:25:45
    trans_id: NA
  intraday_delta_correction:
    long_term_delta_correction: 0.00342574917611221
    short_term_delta_correction: 0.0131432219167099
  intraday_vega_correction:
    historical_vol_mean_reversion: 0.10
    intraday_vega: 0.184532897606929
    long_term_prediction: 0.0879496626746316
  opposite_contract:
    opposite_contract_K: 79.820
    opposite_contract_S: 79.817
    opposite_contract_base_commission: 0.035
    opposite_contract_bs_probability: 0.522961085995045
    opposite_contract_commission_markup: 0.035
    opposite_contract_commission_multiplier: 1
    opposite_contract_discount_rate: 0
    opposite_contract_economic_events_markup: 0.01
    opposite_contract_economic_events_spot_risk_markup: 0.01
    opposite_contract_event_markup: 0
    opposite_contract_historical_vol_markup: 0
    opposite_contract_historical_vol_mean_reversion: 0.10
    opposite_contract_intraday_delta_correction: -0.00828448554641105
    opposite_contract_intraday_eod_markup: 0
    opposite_contract_intraday_historical_iv_risk: 0
    opposite_contract_intraday_vega: -0.184532897606929
    opposite_contract_intraday_vega_correction: -0.00162296060969017
    opposite_contract_long_term_delta_correction: -0.00342574917611216
    opposite_contract_long_term_prediction: 0.0879496626746316
    opposite_contract_mu: 0
    opposite_contract_payout: 1000
    opposite_contract_quiet_period_markup: 0
    opposite_contract_risk_markup: 0.0192266448803464
    opposite_contract_short_term_delta_correction: -0.0131432219167099
    opposite_contract_short_term_kurtosis_risk_markup: 0
    opposite_contract_t: 2.85388127853881e-05
    opposite_contract_vol: 0.122873909065588
    opposite_contract_vol_spread_markup: 0.00922664488034643
  risk_markup:
    economic_events_markup: 0.01
    economic_events_spot_risk_markup: 0.01
    event_markup: 0
    historical_vol_markup: 0
    intraday_eod_markup: 0
    intraday_historical_iv_risk: 0
    quiet_period_markup: 0
    short_term_kurtosis_risk_markup: 0
    vol_spread_markup: 0
slope:
  ask_probability:
    commission_markup: 0.035
    risk_markup: 0.0119069003256586
    theoretical_probability: 0.934234068621166
  bs_probability:
    call_K: 78.300
    call_S: 79.817
    call_discount_rate: 0.0266870816706373
    call_mu: 0
    call_payout: 1000
    call_t: 0.0321427891933029
    call_vol: 0.0721415754540617
  commission_markup:
    base_commission: 0.035
    commission_multiplier: 1
  contract_details:
    ccy: JPY
    description: Win payout if USD/JPY is higher than or equal to 78.300 at close on 2012-11-19.
    loginID: NA
    order_price: 928
    order_type: buy
    payout: 1000
    ref_spot: NA
    ref_vol: NA
    ref_vol2: NA
    short_code: CALLE_FRXUSDJPY_1000_1352345145_1353358800_78300000_0
    slippage_price: NA
    tick_before_trade_time: 79.817
    trade_ask_price: NA
    trade_bid_price: NA
    trade_time: 2012-11-08 03:25:45
    trans_id: NA
  opposite_contract:
    opposite_contract_base_commission: 0.035
    opposite_contract_commission_markup: 0.035
    opposite_contract_commission_multiplier: 1
    opposite_contract_put_K: 78.300
    opposite_contract_put_S: 79.817
    opposite_contract_put_discount_rate: 0.0266870816706373
    opposite_contract_put_mu: 0
    opposite_contract_put_payout: 1000
    opposite_contract_put_slope: -0.0025799239872365
    opposite_contract_put_t: 0.0321427891933029
    opposite_contract_put_vanilla_vega: 1.87944365241045
    opposite_contract_put_vol: 0.0721415754540617
    opposite_contract_put_weight: 1
    opposite_contract_risk_markup: 0.0119069003256586
    opposite_contract_spot_spread_markup: 0.00304711660592641
    opposite_contract_theoretical_probability: 0.0649085019413889
    opposite_contract_vol_spread_markup: 0.0207666840453909
  risk_markup:
    spot_spread_markup: 0.00304711660592641
    vol_spread_markup: 0.0207666840453909
  slope_adjustment:
    call_slope: -0.0025799239872365
    call_vanilla_vega: 1.87944365241045
    call_weight: -1
vana_volga:
  ask_probability:
    commission_markup: 0.035
    risk_markup: 0.0185689913937444
    theoretical_probability: 0.739875144705706
  bs_probability:
    K: 79.500
    S: 79.817
    discount_rate: 0.0266870816706373
    mu: 0
    payout: 1000
    t: 0.0321427891933029
    vol: 0.0688005591685243
  commission_markup:
    base_commission: 0.035
    commission_multiplier: 1
  contract_details:
    ccy: JPY
    description: Win payout if USD/JPY touches 79.500 through close on 2012-11-19.
    loginID: NA
    order_price: 861
    order_type: buy
    payout: 1000
    ref_spot: NA
    ref_vol: NA
    ref_vol2: NA
    short_code: ONETOUCH_FRXUSDJPY_1000_1352345145_1353358800_79500000_0
    slippage_price: NA
    tick_before_trade_time: 79.817
    trade_ask_price: NA
    trade_bid_price: NA
    trade_time: 2012-11-08 03:25:45
    trans_id: NA
  market_supplement:
    Bet_vanna: 10.0585107445883
    Bet_vega: 3.55984913468171
    Bet_volga: -98.0776588866008
    vanna_correction: 0.00500733376810981
    vanna_market_price: 0.00348810600265641
    vanna_survival_weight: 0.14271945608421
    vega_correction: 4.18026404589399e-17
    vega_market_price: 3.46473843989565e-17
    vega_survival_weight: 0.338923488022966
    volga_correction: -0.0134551622822262
    volga_market_price: 0.000404778262771501
    volga_survival_weight: 0.338923488022966
  opposite_contract:
    opposite_contract_Bet_vanna: -10.0514986464373
    opposite_contract_Bet_vega: -3.5556879278898
    opposite_contract_Bet_volga: 97.9849233052805
    opposite_contract_K: 79.500
    opposite_contract_S: 79.817
    opposite_contract_base_commission: 0.035
    opposite_contract_bet_delta: 0.765515811782145
    opposite_contract_bet_vega: 3.5556879278898
    opposite_contract_bs_probability: 0.251318179687812
    opposite_contract_butterfly_greater_than_cutoff: 0
    opposite_contract_commission_markup: 0.035
    opposite_contract_commission_multiplier: 1
    opposite_contract_discount_rate: 0.0266870816706373
    opposite_contract_market_supplement: 0.00843215236812305
    opposite_contract_mu: 0
    opposite_contract_payout: 1000
    opposite_contract_risk_markup: 0.0185531302218208
    opposite_contract_spot_spread: 0.025
    opposite_contract_spot_spread_markup: 0.01
    opposite_contract_spread_to_markup: 2
    opposite_contract_t: 0.0321427891933029
    opposite_contract_theoretical_probability: 0.259750332055935
    opposite_contract_vanna_correction: -0.00501316305678489
    opposite_contract_vanna_market_price: 0.00348810600265641
    opposite_contract_vanna_survival_weight: 0.142985282421034
    opposite_contract_vega_correction: -4.17627076115372e-17
    opposite_contract_vega_market_price: 3.46473843989565e-17
    opposite_contract_vega_survival_weight: 0.338995986114827
    opposite_contract_vol: 0.0688005591685243
    opposite_contract_vol_spread: 0.00762335193452381
    opposite_contract_vol_spread_markup: 0.0271062604436417
    opposite_contract_volga_correction: 0.013445315424908
    opposite_contract_volga_market_price: 0.000404778262771501
    opposite_contract_volga_survival_weight: 0.338995986114827
  risk_markup:
    bet_delta: 0.766414036836472
    bet_vega: 3.55984913468171
    butterfly_greater_than_cutoff: 0
    spot_spread: 0.025
    spot_spread_markup: 0.01
    spread_to_markup: 2
    vol_spread: 0.00762335193452381
    vol_spread_markup: 0.0271379827874887
  theoretical_probability:
    bs_probability: 0.748322973219822
    market_supplement: -0.00844782851411632
